version: "2"
services:
  db:
    container_name: wp-tupipaulista-db
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - wordpress
    environment:
      MYSQL_ROOT_PASSWORD: tupi123456paulista
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: tupi123456paulista

  wordpress:
    depends_on:
      - db
    container_name: wp-tupipaulista-wp
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
    expose:
      - 80
    networks:
      - wordpress
      - nginx-proxy
    environment:
      VIRTUAL_HOST: tupipaulista.thomazot.com.br
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: tupi123456paulista
      LETSENCRYPT_HOST: tupipaulista.thomazot.com.br
      LETSENCRYPT_EMAIL: contato@thomazot.com.br

  pmd:
    depends_on:
      - db
    container_name: wp-tupipaulista-pmd
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    networks:
      - wordpress
      - nginx-proxy
    environment:
      VIRTUAL_HOST: pmd.tupipaulista.thomazot.com.br
      PMA_USERNAME: wordpress
      PMA_PASSWORD: wordpress
      PMA_HOSTS: db
      PHP_MAX_INPUT_VARS: 10000
      LETSENCRYPT_HOST: pmd.tupipaulista.thomazot.com.br
      LETSENCRYPT_EMAIL: contato@thomazot.com.br

networks:
  wordpress:
  nginx-proxy:
    external:
      name: nginx-net
